### ISSUE TITLE
opening file does not work

### ISSUE THREAD

**Issue by jblevins1991** [hundredrabbits/Left#103]
Expected results: open a file and add it to the left sidebar

Actual results: the file does not open

I recently decided to restructure the files I was working with. This involved me deleting 2 files and renaming the rest in windows file explorer. After renaming them, they did not refresh in left. I clicked on one of the files I had deleted or renamed files, a infinite loop of error dialog windows kept popping up. I used task manager to force close left and re-opened it. Only to find that all of the files I renamed were not included. I used the control + o shortcut to open them, but nothing happened.

You should be able to click on the file you want to rename and use the f2 key to rename the file just like any other code editor.

You should be able to click on the file you want to delete and use the delete key to delete a file.

Both of these features would be based on the current file that is selected in the sidebar.

**Comment by mfroach** [comment]
I guess there is still no update on this...? this is a basic feature of the editor not working for me either 👎

**Comment by neauoire** [comment]
> After renaming them, they did not refresh in left. I clicked on one of the files I had deleted or renamed files, a infinite loop of error dialog windows kept popping up.

Is fixed.

There is still no watcher for filechanges after a rename, I am not quite sure how to implement this efficiently.

**Comment by mfroach** [comment]
@neauoire even after cloning github repo the issue persists, this is on windows.

**Comment by mfroach** [comment]
hm, appears it may be an issue with filename. any file I open with hyphens in the filename will not open.

**Comment by neauoire** [comment]
I can only test on Linux/OSX, let me see, it might be something with a way I resolve the icon path on wimdows, this has bit me in the past.

**Comment by neauoire** [comment]
Could you see if you still get this issue with a file named with a single word, like `test.txt`

**Comment by mfroach** [comment]
weird... I'm able to open any file with any type of filename however one empty markdown file will not open

**Comment by neauoire** [comment]
You might be onto something, I never tried opening an empty file. let me check.

**Comment by neauoire** [comment]
Oh yeah, Left can't open empty files!! Fixing [that now](https://github.com/hundredrabbits/Left/issues/114).

**Comment by mfroach** [comment]
👍 many thanks!

**Comment by neauoire** [comment]
Pushed a little fix, could you have a look and tell me if that works for you?
